spring:
  mail:
    host: smtp.gmail.com                #이메일 서버의 호스트명 (여기서는 Gmail의 SMTP 서버)
    port: 587                           #Gmail의 경우 587
    username: simseo034@gmail.com     #Gmail 계정 아이디
    password: ccqsvdntttlmuspc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        debug: true
        connectiontimeout: 5000
        timeout: 5000
        writetimeout: 5000